name : Docker-CI



trigger:
  branches:
    include:
      - master
 
pool:
  vmImage: 'ubuntu-latest'
 
variables:
  ImageName: '172054/juice-app:$(Build.BuildId)'
 
stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker image
    steps:
    - task: Docker@1
      displayName: 'Build the Docker image'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: 'Build an image'
        dockerFile: '**/Dockerfile'
        imageName: '$(ImageName)'
        includeLatestTag: true
        useDefaultContext: false
        buildContext: '.'
     
       
    

    - task: Docker@1
      displayName: 'Push the Docker image to Dockerhub'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: 'Push an image'
        imageName: '$(ImageName)'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
   
    - task: ContainerBuild@0
      inputs:
        dockerRegistryServiceConnection: 'Docker hub'
        Dockerfile: 'Dockerfile'

    - task: PublishCodeCoverageResults@1
      inputs:
       codeCoverageTool: 'JaCoCo'
       summaryFileLocation: 'Lohith1'
    
    - task: HelmInstaller@0
      inputs:
        helmVersion: '2.14.1'
        installKubectl: true

    - task: SonarQubeAnalyze@4
  
    - task: DotNetCoreCLI@2
      inputs:
          command: 'test'
          testRunTitle: 'testing in progress'
          workingDirectory: '/loh'